import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useFetchUser, UserProvider } from "@/lib/authContext";
import LayoutWrapper from "@/components/LayoutWrapper";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movies App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutWrapper>
          <NavBar />
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
